[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.147.2"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -D -F"

[context.branch-deploy]
  command = "hugo -D -F"
