name: Test

on:
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build
        run: hugo --minify
          
      - name: HTML Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: public/
          
      - name: Link Checking
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './public/**/*.html'
          fail: true
          
      - name: Accessibility Testing
        uses: treosh/lighthouse-ci-action@v9
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './.github/lighthouse-config.json'
          
      - name: Performance Testing
        run: |
          npm install -g lighthouse
          lighthouse http://localhost:1313 \
            --chrome-flags="--headless --no-sandbox" \
            --output json \
            --output html \
            --output-path=./lighthouse-report
        
      - name: Upload Performance Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.*
